<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Register.aspx.cs" Inherits="WebApplication1.Register" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:CreateUserWizard ID="CreateUserWizard1" title="Stwórz nowe konto użytkownika" onnextbuttonclick="LinkButton1_Click" OnCreatedUser="LinkButton1_Click" runat="server" AnswerLabelText="Tajna odpowiedź:" AnswerRequiredErrorMessage="Tajna odpowiedź jest wymagana." CancelButtonText="Anuluj" CompleteSuccessText="Twoje konto zostało pomyślnie utworzone." ConfirmPasswordCompareErrorMessage="Hasło oraz jego potwierdzenie muszą być identyczne." ConfirmPasswordLabelText="Potwierdź hasło:" ConfirmPasswordRequiredErrorMessage="Potwierdzenie hasła jest wymagane." ContinueButtonText="Kontynuuj" CreateUserButtonText="Zarejestruj się" DuplicateEmailErrorMessage="" DuplicateUserNameErrorMessage="Takie konto już istnieje. Wybierz inną nazwę użytkownika." EmailRegularExpressionErrorMessage="" EmailRequiredErrorMessage="Email jest niepoprawny." FinishCompleteButtonText="Zakończ" FinishPreviousButtonText="Wstecz" InvalidAnswerErrorMessage="Uzupełnij tajną odpowiedź." InvalidEmailErrorMessage="Popraw wpisany email." InvalidPasswordErrorMessage="" InvalidQuestionErrorMessage="Uzupełnij tajne pytanie." PasswordLabelText="Hasło:" PasswordRegularExpressionErrorMessage="" PasswordRequiredErrorMessage="Hasło jest wymagane." QuestionLabelText="Tajne pytanie:" QuestionRequiredErrorMessage="Tajne pytanie jest wymagane." StartNextButtonText="Dalej" StepNextButtonText="Dalej" StepPreviousButtonText="Wstecz" UnknownErrorMessage="Twoje konto nie zostało utworzone. Spróbuj ponownie." UserNameLabelText="Nazwa użytkownika:" UserNameRequiredErrorMessage="Nazwa użytkownika jest wymagana.">
        <WizardSteps>
            <asp:CreateUserWizardStep runat="server" />
            <asp:CompleteWizardStep runat="server" />
        </WizardSteps>
    </asp:CreateUserWizard>
</asp:Content>
